export enum ErrorType {
  INVALID_REQUEST = "INVALID_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  SERVER_ERROR = "SERVER_ERROR",
  NETWORK_ERROR = "NETWORK_ERROR",
  REQUEST_SETUP_ERROR = "REQUEST_SETUP_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}
